language: cpp
compiler: gcc
dist: trusty
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
install:
- sudo apt-get install -qq g++-5
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
script:
- g++ --version
- c++ --version
- git submodule update --init --recursive
- "./build.sh"
services:
- mysql
env:
  global:
  - secure: bbWe7xRDdcgxhrIDjsogWTZxw2xbSb1e7po5w1S5em3YXFO9N+nytlorLsdXlY1uXX7xZ7NK8F11lfyyjIZmbe2So4ievnYHfh40Qm13OLI9+dO0q5lSakHnO+70DUq+inT2DOFhRNkXXvjOBZ6F+rBVvX1ueDgBqqjX7xSqEeHIzcMyXYAVjSegVv8HsrfMpnsiQBPH8f2fj2ZcGU+GIqx0FvGg8CUi4FNeI7ry5Z4n6xfZZ1Gd0V5kJYcFEQmrLvvcSjlVtUBe/sIXUta7lnXM1rMKe+ATPtU6siFN/Z9PtrAXBA4dTkkriw2zsrwt5IvrbGppTOVqd9V0E31QtQiaIcT+UT4oNzOD8Gm5mR9HZBLXwdiJGpMP5sNZqnGxfgWHi7bEov3wiRGh2A9mSnuFtaSFRbS+oAClPzAZq6slSfDrlQUnGYrOuzDAfM6Xm2RHHOMalfzqPnmxXDEDpj6W7oIfLSYNr0t9HaPbgPNHvvi3ayzQ4W7KW4W1ase90C2c0itaVBrTB+8g6XgzQl2UmkM/KGMEpJjQKVMqW/V9g6KHhxrhfPhMXE50IHAYJW+SADdWm25bURygkFhyEbAj6geogZeFA0MrjfK5uT2dwK3dCK0KpC5dcrcJqSv87Hk7qkPMwwCd/+o4yI65gXFY2nYCl8L/ujvmI/7damw=
  - secure: qA8yfYL+k7TR7C+ZfQJ970rMGV4LoOd9qQVYvi3JV8I7eZD0LDD0cx5o0RPDYzi+Mjh0QT80H4a6TdW489edfY5+2MktcvXrHzuEI4LYV9yteotC87SLjXUnocEkqGohTf/hrVLi1HYheNa9e/jxLBuBWsw6/XrkzIIKCe3sdflF66iVEOasPIiYealxZu/+3CMaSVVDJjGgtdU49yeVp7pszkv/5QNnxELwfmxxXOdThf3iFVa/SPiCJWkoPBwp78gj70bWMbd/vAwL67ijlFlhKqYOyo2UskQ9DOdO0sZglMfzOl1Gy+XHZprNZVCly78ci0ikRdDro3jEhNqNgA8o/G3kgOSRNjIxAUzYBKzVMOI+R4NkKPdaeVgcX2XYs6sQe1PcAeU8gmLTIM/2OkFhU5BZ5ToouEBiRfYUXRei3cTT3Q6r9W/XiMfPGIkKIYHCTz0RnEDqKY9yG3BLiD7HALWjHp+ofD7VKDZ9i54+f6ZlJYGS7Cz5VSGYMdMtTCDGYSkOrOP82yPQeWxV/KRGdtJfYpmch/h7bPwDwKb1GBmOFpmbh3pAYQ+OrnLc1mdytQ44pINvs9UolQahMy43hc17Dif+ndhVcFUORfYDISJpN0uqC6qNLXSFRWOqxG+RcxwZiBHdzADPZW7KXk6tg9JHKHoddeezcqBKUXo=
  - secure: SfKIRGiXi6BdXXxgEZVur6iQb02/JSwIRTnSZRbtpd4tJtnh92PqgAK+Jw18bKWP95q3uLYaKWcWBeXZtHZhdfmzRmNjkLAWqWhUC+5tEy0axAZn2bXFI6TtpmqXem/BAzv5Ja0ZJLZehj+BuPXWmglJJlt7YA717/2ZGGo8SKq3AkUP2F/EJ91jWYd2rLtPLntTiWBH9TZxXpuGlAbIL5SyFftkQDpReBOM9GlqBnJdOjaHPHbRA5lsdKn6KZ5nHJtsWg7mGn1AXaA+WzRcjZfLww4a2BK9Y2K1/jSIHttJAKPFyX2oHifa95bufxUHw7EKHCqxjOkZP8rhZVT/CTtR1mN8NnI4SkB7CRx/tubFV8+jTlAUrY284KDzcYglKi5RoA58AygqZBqhbluyGcjkopiRSD3+NH2+zwZxZq8QoWBcf0+J6PiFUO5n3p1kk84oCST+kMPy5FbMrPH6+pdFiN2W9180DmAqEFteMe1p40C4tsWXR7j/v06jQJzW7U0GN/GhGMg460+oUGqUbly3x4Dfen4mZp3cioYsXIRMdBDA0IwNOOwKWswOU/d6l8al9ZfjBYgID4u3tuIdILjTVn9S/wFjTsPy4C+TrVQaZOKbos5BXXdP/N9kPMN9mtx3iXJNbiQdWPVxDvlpsgu2Og2YVR8QaNW9BkwOtnY=
